### ISSUE TITLE
Deploy Image

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/fc-alibaba#18]
- [ ] 如果用户不指定命名空间和仓库的情况，默认帮助用户创建。
- [ ] 如果用户不写CrAccount，默认让用户在命令行填写（走Fun的逻辑）

**Comment by dengshenyu** [comment]
如果用户不指定命名空间和仓库的情况，默认帮助用户创建 => 会默认创建${accountId}-serverless命名空间，仓库名称为${serviceName}-${functionName}
如果用户不写CrAccount，默认会走临时秘钥登录；如果临时秘钥登录失败，会fallback到原用户context，和fun一样
