### ISSUE TITLE
Deploy模式变化

### ISSUE THREAD

**Issue by anycodes** [Serverless-Devs/fc-alibaba#20]
- [ ] s deploy --config
- [ ] s deploy --service-config
- [ ] s deploy --function-config
- [ ] s deploy --function
- [ ] s deploy --function-code
- [ ] s deploy --tags
- [ ] s deploy --domain
- [ ] s deploy --trigger

**Comment by coco-super** [comment]
![image](https://user-images.githubusercontent.com/48934955/94238593-3082ed80-ff43-11ea-9509-2a7bb6111885.png)
